### ISSUE TITLE
Error on installation - AttributeError: 'list' object has no attribute 'split'

### ISSUE THREAD

**Issue by jdittmann** [KathrynJones1/catwoman#15]
Installing the software via pip (as well as when downloading the repository and attempting to build) yields the following error using python 3.

pip install catwoman
Collecting catwoman
  Using cached catwoman-1.0.13.tar.gz (32 kB)
  Installing build dependencies ... [?25ldone
etting requirements to build wheel ... [?25ldone
g metadata (pyproject.toml) ... [?25lerror
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [46 lines of output]
      Checking for OpenMP support...
      Did not detect OpenMP support.
      /private/var/folders/zr/vshpxw6109d4zxplx1nsp7b40000gn/T/pip-build-env-pik33xho/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py:257: UserWarning: Unknown distribution option: 'extras_requires'
        warnings.warn(msg)
      running dist_info
      creating /private/var/folders/zr/vshpxw6109d4zxplx1nsp7b40000gn/T/pip-modern-metadata-r1tzy4ei/catwoman.egg-info
      writing /private/var/folders/zr/vshpxw6109d4zxplx1nsp7b40000gn/T/pip-modern-metadata-r1tzy4ei/catwoman.egg-info/PKG-INFO
      Traceback (most recent call last):
        File "/Users/ankylosaurus/opt/anaconda3/envs/Fixed_Python/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/Users/ankylosaurus/opt/anaconda3/envs/Fixed_Python/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/ankylosaurus/opt/anaconda3/envs/Fixed_Python/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 164, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/private/var/folders/zr/vshpxw6109d4zxplx1nsp7b40000gn/T/pip-build-env-pik33xho/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 188, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/private/var/folders/zr/vshpxw6109d4zxplx1nsp7b40000gn/T/pip-build-env-pik33xho/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 281, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/private/var/folders/zr/vshpxw6109d4zxplx1nsp7b40000gn/T/pip-build-env-pik33xho/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 174, in run_setup
          exec(code, locals())
        File "<string>", line 78, in <module>
        File "/private/var/folders/zr/vshpxw6109d4zxplx1nsp7b40000gn/T/pip-build-env-pik33xho/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/private/var/folders/zr/vshpxw6109d4zxplx1nsp7b40000gn/T/pip-build-env-pik33xho/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 177, in setup
          return run_commands(dist)
        File "/private/var/folders/zr/vshpxw6109d4zxplx1nsp7b40000gn/T/pip-build-env-pik33xho/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 193, in run_commands
          dist.run_commands()
        File "/private/var/folders/zr/vshpxw6109d4zxplx1nsp7b40000gn/T/pip-build-env-pik33xho/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
          self.run_command(cmd)
        File "/private/var/folders/zr/vshpxw6109d4zxplx1nsp7b40000gn/T/pip-build-env-pik33xho/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/private/var/folders/zr/vshpxw6109d4zxplx1nsp7b40000gn/T/pip-build-env-pik33xho/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/private/var/folders/zr/vshpxw6109d4zxplx1nsp7b40000gn/T/pip-build-env-pik33xho/overlay/lib/python3.9/site-packages/setuptools/command/dist_info.py", line 35, in run
          egg_info.run()
        File "/private/var/folders/zr/vshpxw6109d4zxplx1nsp7b40000gn/T/pip-build-env-pik33xho/overlay/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 300, in run
          writer(self, ep.name, os.path.join(self.egg_info, ep.name))
        File "/private/var/folders/zr/vshpxw6109d4zxplx1nsp7b40000gn/T/pip-build-env-pik33xho/overlay/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 664, in write_pkg_info
          metadata.write_pkg_info(cmd.egg_info)
        File "/private/var/folders/zr/vshpxw6109d4zxplx1nsp7b40000gn/T/pip-build-env-pik33xho/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 1136, in write_pkg_info
          self.write_pkg_file(pkg_info)
        File "/private/var/folders/zr/vshpxw6109d4zxplx1nsp7b40000gn/T/pip-build-env-pik33xho/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 197, in write_pkg_file
          write_field('License', rfc822_escape(license))
        File "/private/var/folders/zr/vshpxw6109d4zxplx1nsp7b40000gn/T/pip-build-env-pik33xho/overlay/lib/python3.9/site-packages/setuptools/_distutils/util.py", line 518, in rfc822_escape
          lines = header.split('\n')
      AttributeError: 'list' object has no attribute 'split'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by nespinoza** [comment]
Hey @KathrynJones1! This has an easy fix: changing the license from a list to a string in `setup.py` as here: https://github.com/lkreidberg/batman/pull/49/commits/5297390f67e869decf411ff3d681e8fe75a01a1b

This was also a `batman` problem, and got fixed doing this. I have it fixed on a local copy as well, but can't seem to push the change to this repo. If you could do this, that would be great! Otherwise, can fix this on Wednesday.

N.
