### ISSUE TITLE
`setup.py` requires numpy

### ISSUE THREAD

**Issue by barentsen** [KathrynJones1/catwoman#2]
(Posted in relation to openjournals/joss-reviews#2382.)

## Issue

It is not currently possible to `pip install catwoman` in a fresh environment, because `setup.py` requires `numpy` to be installed:

```bash
$ python -m venv tmpenv
$ source tmpenv/bin/activate
$ pip install catwoman
Collecting catwoman
  Using cached https://files.pythonhosted.org/packages/b8/79/c463b58dd82d3360ce820ff263956f8804113a213b36ce7d38101275be56/catwoman-1.0.4.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /home/gb/tmp/tmpenv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-unsajkma/catwoman/setup.py'"'"'; __file__='"'"'/tmp/pip-install-unsajkma/catwoman/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-unsajkma/catwoman/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-unsajkma/catwoman/setup.py", line 5, in <module>
        import numpy as np
    ModuleNotFoundError: No module named 'numpy'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 20.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

## Solution

A few different solutions exist (cf. stackoverflow).  I believe the easiest solution will be to create a `pyproject.toml` file in the root directory of the project, which is used by modern versions of `pip` to install reqiurements needed before running `setup.py`.  The file should contain something like this:
```
[build-system]
requires = ["setuptools", "wheel", "numpy"]
````

**Comment by KathrynJones1** [comment]
Thank you for this issue!  I have had a look at the `setup.py` file and tried adding 
`setup_requires=['wheel', 'numpy']` and it appeared to install when I created a new environment:

```
$ python -m venv env
$ source env/bin/activate
$ pip install catwoman
Collecting catwoman
  Downloading https://files.pythonhosted.org/packages/68/93/b0066fe24be50d80c1b33e1a064e1ff5839da703f552cc5af4cfe68cd3ac/catwoman-1.0.5-cp37-cp37m-macosx_10_7_x86_64.whl (76kB)
    100% |████████████████████████████████| 81kB 1.1MB/s 
Collecting numpy (from catwoman)
  Using cached https://files.pythonhosted.org/packages/5c/f5/0e5e57fa7683cf0e5036320f4676cd7e3dbd9ab8c17ada541c2bb5ebed5e/numpy-1.19.0-cp37-cp37m-macosx_10_9_x86_64.whl
Installing collected packages: numpy, catwoman
Successfully installed catwoman-1.0.5 numpy-1.19.0
```
Let me know if this works now for you now? If not I will try the solution you suggested.

**Comment by barentsen** [comment]
Mmmm, this still doesn't work for me:

```
$ python -m venv tmpenv
$ source tmpenv/bin/activate
$ pip install catwoman
Collecting catwoman
  Downloading https://files.pythonhosted.org/packages/a4/af/e026ab937ff6baaa5b6e44b5d5a33fbbd192814deace3812a5c7897dfaa3/catwoman-1.0.5.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /home/gb/tmp/tmpenv/bin/python -c 'import sys, setuptools, tokenize;
 sys.argv[0] = '"'"'/tmp/pip-install-np_cw02a/catwoman/setup.py'"'"';
 __file__='"'"'/tmp/pip-install-np_cw02a/catwoman/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);
code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))'
egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-np_cw02a/catwoman/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-np_cw02a/catwoman/setup.py", line 5, in <module>
        import numpy as np
    ModuleNotFoundError: No module named 'numpy'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

The reason we see different behavior is that my version of `pip` attempts to install `catwoman` from source because I'm using Linux.  In your case `pip` installs the wheel file (cf. line that says `Downloading ... catwoman-1.0.5-cp37-cp37m-macosx_10_7_x86_64.whl`).  Wheel files are great because they allow `pip` to skip `setup.py` entirely and install the package by copying pre-compiled files.  You will have created those wheel files when you typed `python setup.py bdist_wheel`.  These pre-compiled wheel files are platform-specific however, and so pip will only use them for OSX users, whereas I'm using Linux.

### Solution

The reason that adding `numpy` to `setup_requires` doesn't work when installing from source is that `setup.py` contains `import numpy` at the top, so the script fails before it can inform pip about the contents of `setup_requires`.  Python introduced the `pyproject.toml` file mechanism exactly to solve this type of problem, so adding it will likely be the best solution!

(An alternative solution would be to pre-compile wheels for *every* platform, but that is way more complicated because it requires access to multi-platform build servers!)

**Comment by KathrynJones1** [comment]
Ah okay I understand now, I have added the `pyproject.toml` file to the root directory and updated the pypi version - let me know if that works now!

**Comment by barentsen** [comment]
I confirm installation in a new environment works now! Awesome :+1:

```bash
$ pip install catwoman
Collecting catwoman
  Downloading https://files.pythonhosted.org/packages/95/b7/a9be27b99d2f64554a4768c1d3e2790cd4e82ddcc26e31b87df4b9e7f6b1/catwoman-1.0.6.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting numpy (from catwoman)
  Using cached https://files.pythonhosted.org/packages/57/55/5366b0afed57facaf887b05f0e98c887a9e27021e3f4e78a26a6d535e538/numpy-1.19.0-cp38-cp38-manylinux2010_x86_64.whl
Building wheels for collected packages: catwoman
  Building wheel for catwoman (PEP 517) ... done
  Created wheel for catwoman: filename=catwoman-1.0.6-cp38-cp38-linux_x86_64.whl size=111306 sha256=8c3d4e21e1ccbf3cd3466db7a6e75c859dfa4216eddc9fbfb70c1eff2fb5d405
  Stored in directory: /home/gb/.cache/pip/wheels/ff/a1/e6/50ee52f47ce80bb42fff94bb6c60d06fd8b332144e599c9000
Successfully built catwoman
Installing collected packages: numpy, catwoman
Successfully installed catwoman-1.0.6 numpy-1.19.0
```

However, importing the package doesn't work yet because the `batman` dependency is missing:

```bash
$ python -c "import catwoman"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/gb/tmp/tmpenv/lib/python3.8/site-packages/catwoman/__init__.py", line 8, in <module>
    from .plots import *
  File "/home/gb/tmp/tmpenv/lib/python3.8/site-packages/catwoman/plots.py", line 27, in <module>
    import batman
ModuleNotFoundError: No module named 'batman'
```

It should be sufficient to add `batwoman` to `install_requires` in `setup.py` to resolve this.

**Comment by KathrynJones1** [comment]
Okay, I've had a look and I've removed the `batman` dependency as it isn't necessary for the code - so that should work now? (newest version is now 1.0.7)

**Comment by barentsen** [comment]
Ok!  Installation via pip seems to work now! :+1:

```bash
$ python -m venv tmpenv
$ source tmpenv/bin/activate
$ pip install catwoman
Collecting catwoman
  Downloading https://files.pythonhosted.org/packages/bd/e0/1ab42115b03728e734effa0fa5d47b9d3854e5b7172b70a564a995cb8546/catwoman-1.0.7.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting numpy (from catwoman)
  Using cached https://files.pythonhosted.org/packages/57/55/5366b0afed57facaf887b05f0e98c887a9e27021e3f4e78a26a6d535e538/numpy-1.19.0-cp38-cp38-manylinux2010_x86_64.whl
Building wheels for collected packages: catwoman
  Building wheel for catwoman (PEP 517) ... done
  Created wheel for catwoman: filename=catwoman-1.0.7-cp38-cp38-linux_x86_64.whl size=111312 sha256=6e8483195977d501a8c37b043949d48d4be8d351a51100779abf2734163a3d88
  Stored in directory: /home/gb/.cache/pip/wheels/c4/b7/81/5eeddbc85db5c605f9f3182cd301ee94de1831a10294f5eaa4
Successfully built catwoman
Installing collected packages: numpy, catwoman
Successfully installed catwoman-1.0.7 numpy-1.19.0
$ python -c "import catwoman; print(catwoman.__version__)"
1.0.7
```
